### ISSUE TITLE
Advanced Initialization Methods

### ISSUE THREAD

**Issue by drckf** [drckf/paysage#12]
Minibatch versions of k-means, PCA, and archetype analysis can provide reasonable initial guesses for the parameters of latent variable models. Mean-field methods for RBMs: https://arxiv.org/abs/1702.03260

**Comment by d-rams** [comment]
Actually even a simple statistical initializer will do better than what we have. In my experiments with tap-machines I found that nothing would train with the default weight initialization of .01 * Uniform(-1,1).

**Comment by d-rams** [comment]
For instance we could do something like Glorot uniform a la http://jmlr.org/proceedings/papers/v9/glorot10a/glorot10a.pdf

Not sure how this relates to latent variable models like RBMs vs feed-forward NNs

**Comment by d-rams** [comment]
glorot normal and PCA are implemented
