### ISSUE TITLE
Offset values in the energy function

### ISSUE THREAD

**Issue by AdrianLsk** [drckf/paysage#37]
All non-binary D/RBMs augment the basic (binary case) energy function with other terms based on the distribution of visible units. This is even more evident when using supervised or temporal RBMs or for efficient learning of joint DBMs (centering of hidden representations). Since the log energy function is always a linear function of hidden and visible units, all of these more complicated terms can be added as an offset to the basic formula (this can be done in a smart way also for the free energy function, by saving intermediate calculations into separate terms and reuse them later). So it would be nice to keep it in mind when designing the base classes.

**Comment by drckf** [comment]
This is an important point that we are currently working on, as referenced in Issue #24.
