### ISSUE TITLE
Layer-by-layer training of deep models

### ISSUE THREAD

**Issue by drckf** [drckf/paysage#5]
http://www.jmlr.org/proceedings/papers/v5/salakhutdinov09a/salakhutdinov09a.pdf
https://papers.nips.cc/paper/4610-a-better-way-to-pretrain-deep-boltzmann-machines.pdf
http://www.cs.cmu.edu/~rsalakhu/papers/dbmrec.pdf

**Comment by AdrianLsk** [comment]
There is a better and more effective way to train the DBMs jointly without pretrianing:
http://www-etud.iro.umontreal.ca/~goodfeli/mp_dbm.pdf
https://arxiv.org/pdf/1301.3568.pdf

Those papers are for classification, but the same principle applies also for unsupervised training. pylearn2 has it implemented for both: https://github.com/lisa-lab/pylearn2/tree/master/pylearn2/models/dbm, but it's very hard to read.

**Comment by drckf** [comment]
Resolved by #111
