### ISSUE TITLE
Updated backend with GPU support

### ISSUE THREAD

**Issue by drckf** [drckf/paysage#6]
Paysage is being designed to use multiple backends. Currently, there are:
-- a numpy/numexp/numba backend 
-- a backend that uses (pytorch)[https://github.com/pytorch/pytorch] (in progress)

**Comment by AdrianLsk** [comment]
What it the current state of this issue? Are there any plans to use autograd in the future? And how about to use just PyTorch backend, but with a support for both CPU and GPU instead of maintaining two backends?

**Comment by drckf** [comment]
Currently, we support both a Numpy/Numexpr backend and a PyTorch backend, which can run on either the CPU or GPU in principle. There is a possibility that we drop the Numpy/Numexpr backend at some point, but probably not anytime soon. So far, we haven't found it very onerous to maintain both backends.

**Comment by drckf** [comment]
Resolved by #111
