### ISSUE TITLE
Deprecate marginal_free_energy

### ISSUE THREAD

**Issue by drckf** [drckf/paysage#85]
We should convert the `EnergyGap` and `EnergyZScore` methods to use the `joint_energy` instead of the `marginal_free_energy` because the former is well-defined for deep models whereas the latter is not really computable. In fact, we should probably deprecate the marginal_free_energy function, which may simplify the code a bit.  

This is really easy to fix, so we should just do it.

**Comment by d-rams** [comment]
Merged pr #86
