### ISSUE TITLE
Capsules

### ISSUE THREAD

**Issue by drckf** [drckf/paysage#9]
http://www.cs.toronto.edu/~fritz/absps/transauto6.pdf

**Comment by geminatea** [comment]
Here is Sida Wang's thesis: http://nlp.stanford.edu/~sidaw/home/_media/papers:thesis.pdf

**Comment by geminatea** [comment]
Along with an implementation: https://github.com/yingzha/Transforming-Autoencoders

I can't vouch for the quality of it.
